name: Actions workflow
on: [push]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run:  |
          pwd
          ls
      - name: Simple js Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Hamfri
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
