name: Actions workflow
on: 
  push:
    branches:
      - "main"
  #schedule:
  # - cron: "*/5 * * * *"
  repository_dispatch:
    types: [build]
  pull_request:
    types: [assigned, opened, reopened]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Client payload
        run: echo ${{ github.event.client_payload.env }}
      - name: List files
        run: |
          pwd
          ls -al
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          # git clone git@github:$GITHUB_REPOSITORY
          # git checkout $GITHUB_SHA
      - name: Simple js Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Hamfri
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
